# Generated by Django 6.0.2 on 2026-02-17 18:25

from django.db import migrations, models
from django.utils.text import slugify


def _build_unique_slug(model, source_value, current_pk):
    base_slug = slugify(source_value) or "item"
    slug = base_slug
    counter = 2

    while model.objects.filter(slug=slug).exclude(pk=current_pk).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1

    return slug


def populate_slugs(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')

    for category in Category.objects.all():
        if not category.slug:
            category.slug = _build_unique_slug(Category, category.name, category.pk)
            category.save(update_fields=['slug'])

    for product in Product.objects.all():
        if not product.slug:
            product.slug = _build_unique_slug(Product, product.name, product.pk)
            product.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
